WManager/Controllers/ArtikalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WManager.Models;

namespace WManager.Controllers
{
    [Authorize]
    public class ArtikalController : Controller
    {
        ApplicationDbContext context;
        public ArtikalController()
        {
            context = new ApplicationDbContext();
        }

        /// <summary>
        /// Vraca listu artikala
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            List<Artikal> Artikli = context.Artikli.ToList();
            return View(Artikli);
        }

        /// <summary>
        /// Vraca stranicu za unos artikla
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult UnesiNoviArtikal()
        {
            return View();
        }

        /// <summary>
        /// Vrsi unos novog artikla u bazu
        /// </summary>
        /// <param name="artikal">novi artikal</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UnesiNoviArtikal(Artikal artikal)
        {
            if(ModelState.IsValid)
            {
                context.Artikli.Add(artikal);
                context.SaveChanges();
                TempData["AlertSuccess"] = "uspesno kreiran novi artikal!";
                return RedirectToAction("Index");

            }
            TempData["AlertError"] = "Doslo je do greske prilikom unosa artikla";
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Vraca stranicu za izmenu artikla
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult IzmeniArtikal()
        {
            return View();
        }

        /// <summary>
        /// Vrsi izmenu artikla
        /// </summary>
        /// <param name="artikal">Artikal popunjen novim podacima</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult IzmeniArtikal(Artikal artikal)
        {
            if (ModelState.IsValid)
            {
                Artikal stari = context.Artikli.FirstOrDefault(x => x.Barkod == artikal.Barkod);
                if (stari != null)
                { 
                    stari.Kolicina = artikal.Kolicina;
                    stari.Naziv = artikal.Naziv;
                    stari.ZemljaPorekla = artikal.ZemljaPorekla;
                    stari.Proizvodjac = artikal.Proizvodjac;

                    context.SaveChanges();
                    TempData["AlertSuccess"] = "Uspesno izmenjen artikal!";
                    return RedirectToAction("Index");
                }
            }
            TempData["AlertError"] = "Doslo je do greske prilikom izmene artikla!";
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Vraca stranicu za brisanje artikla
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Authorize(Roles ="Menadzer")]
        public ActionResult BrisanjeArtikla()
        {
            return View();
        }

        /// <summary>
        /// Vrsi brisanje artikla sa prosledjenim bar kodom
        /// </summary>
        /// <param name="Barkod">Barkod artikla za brisanje</param>
        /// <returns></returns>
        [Authorize(Roles = "Menadzer")]
        [HttpPost]
        public ActionResult BrisanjeArtikla(string Barkod)
        {
            Artikal zaBrisanje = context.Artikli.FirstOrDefault(x => x.Barkod == Barkod);
            if(zaBrisanje != null)
            {
                context.Artikli.Remove(zaBrisanje);
                context.SaveChanges();
                TempData["AlertSuccess"] = "uspesno obrisan artikal!";
                return RedirectToAction("index");
            }
            TempData["AlertError"] = "Doslo je do greske prilikom brisanja artikla!";
            return RedirectToAction("index");
        }

        /// <summary>
        /// Vraca stranicu za skidanje artikla sa stanja
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult SkidanjeSaStanja()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SkidanjeSaStanja(string Barkod, int Kolicina)
        {
            Artikal artikal = context.Artikli.FirstOrDefault(x => x.Barkod == Barkod);
            if(artikal != null)
            {
                artikal.Kolicina -= Kolicina;
                context.SaveChanges();
                TempData["AlertSuccess"] = "uspesno skinuto sa stanja!";
                return RedirectToAction("index");
            }
            TempData["AlertError"] = "Doslo je do greske prilikom skidanja artikla sa stanja!";
            return RedirectToAction("index");
        }
        /// <summary>
        /// Vraca stranicu za unos parametara pretrage
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult PretragaArtikala()
        {
            return View();
        }

        /// <summary>
        /// Vrsi pretragu artikala po prosledjenim parametrima
        /// </summary>
        /// <param name="Barkod"></param>
        /// <param name="Naziv"></param>
        /// <param name="ZemljaPorekla"></param>
        /// <param name="Proizvodjac"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult TraziArtikal(string Barkod = "", string Naziv = "", string ZemljaPorekla = "", string Proizvodjac = "")
        {
            IQueryable<Artikal> rezultat = context.Artikli;
            if(Barkod != "")
            {
                rezultat = rezultat.Where(x => x.Barkod == Barkod);
            }
            if(Naziv != "")
            {
                rezultat = rezultat.Where(x => x.Naziv == Naziv);
            }
            if(ZemljaPorekla != "")
            {
                rezultat = rezultat.Where(x => x.ZemljaPorekla == ZemljaPorekla);
            }
            if(Proizvodjac != "")
            {
                rezultat = rezultat.Where(x => x.Proizvodjac == Proizvodjac);
            }
            List<Artikal> artikli = rezultat.ToList();
            if(artikli.Count == 1)
            {
                return View("DetaljiArtikla",artikli[0]);
            }
            return View(artikli);
        }
        /// <summary>
        /// Za ajax, vrsi proveru da li artikal postoji i vraca status kod i artikal
        /// status kodovi: 0-nijeNadjen 1-nadjen 2-Neka druga greska
        /// </summary>
        /// <param name="Barkod">Barkod artikla koji se trazi</param>
        /// <returns></returns>
        [HttpPost] 
        public JsonResult TraziArtikal(string Barkod = "0")
        {
            if(Barkod == null)
            {
                return Json(new { status = 2 });
            }

            if (Barkod.Length == 13)
            {
                Artikal a = context.Artikli.FirstOrDefault(x => x.Barkod == Barkod);
                if (a != null)
                {
                    return Json(new { status = 1, artikal = a });
                }
                else
                {
                    return Json(new { status = 0 });
                }
            }
            else
            {
                return Json(new { status = 2 });
            }
        }
    }
}

WManager/Controllers/RadnikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WManager.Models;

namespace WManager.Controllers
{
    [Authorize(Roles = "Menadzer")]
    public class RadnikController : Controller
    {
        ApplicationDbContext context;
        public RadnikController()
        {
            context = new ApplicationDbContext();
        }
        /// <summary>
        /// Prikazuje listu radnika
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            
            return View(context.Users.ToList());
        }
        /// <summary>
        /// Prikazuje stranicu za izmenu radnika
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult IzmenaRadnika()
        {
            return View();
        }
        /// <summary>
        /// Vrsi izmenu podataka o radniku u bazi.
        /// </summary>
        /// <param name="radnik">izmenjeni radnik</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult IzmenaRadnika(ApplicationUser radnik)
        {
           
                ApplicationUser stari = context.Users.FirstOrDefault(x => x.Email == radnik.Email);
                if (stari != null)
                {
                    stari.FirstName = radnik.FirstName;
                    stari.LastName = radnik.LastName;
                    stari.PhoneNumber = radnik.PhoneNumber;
                    stari.UserName = radnik.UserName;
                    stari.Email = radnik.UserName; //Username i email su prakticno isti. Na stranici za izmenu se username koristi za izmenu, a email za proveru postojanja
                    context.SaveChanges();
                    TempData["AlertSuccess"] = "uspesno izmenjen radnik!";
                    return RedirectToAction("Index");
                }
            
            TempData["AlertError"] = "Doslo je do greske prilikom izmene radnika";
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Vraca stranicu za brisanje radnika
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult BrisanjeRadnika()
        {
            return View();
        }
        /// <summary>
        /// Brise radnika iz baze
        /// </summary>
        /// <param name="Email">Imejl adresa radnika za brisanje</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult BrisanjeRadnika(string Email)
        {
            ApplicationUser zaBrisanje = context.Users.FirstOrDefault(x => x.Email == Email);
            if(zaBrisanje != null)
            {
                context.Users.Remove(zaBrisanje);
                context.SaveChanges();
                TempData["AlertSuccess"] = "uspesno obrisan radnik!";
                return RedirectToAction("Index");
            }

            TempData["AlertError"] = "Doslo je do greske prilikom brisanja radnika";
            return RedirectToAction("Index");
        }
        /// <summary>
        /// vraca stranicu za trazenje radnika
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult TraziRadnika()
        {
            return View();
        }
        /// <summary>
        /// Prikazuje rezultate pretrage
        /// </summary>
        /// <param name="Email"></param>
        /// <param name="FirstName"></param>
        /// <param name="LastName"></param>
        /// <param name="PhoneNumber"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult PretragaRadnika(string Email = "", string FirstName = "", string LastName = "", string PhoneNumber = "")
        {
            IQueryable<ApplicationUser> kveri = context.Users;
            if (Email != "")
            {
                kveri = kveri.Where(x => x.Email == Email);
            }
            if(FirstName != "")
            {
                kveri = kveri.Where(x => x.FirstName == FirstName);
            }
            if(LastName != "")
            {
                kveri = kveri.Where(x => x.LastName == LastName);
            }
            if(PhoneNumber != "")
            {
                kveri = kveri.Where(x => x.PhoneNumber == PhoneNumber);
            }
            List<ApplicationUser> radnici = kveri.ToList();
            if(radnici.Count == 1)
            {
                return View("DetaljiRadnika", radnici[0]);
            }
            return View(radnici);
        }
        /// <summary>
        /// Za ajax, vrsi proveru da li radnik postoji i vraca status kod i radnika
        /// status kodovi: 0-nijeNadjen 1-nadjen 2-Neka druga greska
        /// </summary>
        /// <param name="Email">Email radnika koga trazimo</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult TraziRadnika(string Email = "")
        {
            if (Email == "")
            {
                return Json(new { status = 2 });
            }

            ApplicationUser radnik = context.Users.FirstOrDefault(x => x.Email == Email);
            if (radnik != null)
            {
                return Json(new { status = 1, radnik = radnik });
            }
            else
            {
                return Json(new { status = 0 });
            }


        }
    }
}

WManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/myStyles")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container header-nav">
            <div class="navbar-heade header-navr">
                <button class="toggleSidebar" onclick="openSidebar('sidebar')"> <img src="~/Content/Images/menu.png" alt="• • •" class="menu-img" /> </button>
            </div>
            <button class="nav navbar-nav navbar-left btnHome">@Html.ActionLink("Home", "Index", "Home")</button>
            <div>
                
                    <ul class="nav navbar-nav nav-sidebar" id="sidebar" style="display:none;">

                        @*zameniti nazive*@

                        <li class="sideItem" onclick="openSubitem('subitem')" style="padding-top: 10px; padding-bottom: 10px; line-height: 20px;">
                            Artikli
                        </li>
                        <li>
                            <ul class="nav navbar-nav subitem" id="subitem" style="display:none; width: 100% !important">
                                <li>@Html.ActionLink("Lista artikala", "Index", "Artikal")</li>
                                @if (User.IsInRole("Menadzer"))
                                {
                                    <li>@Html.ActionLink("Novi artikal", "UnesiNoviArtikal", "Artikal")</li>
                                }
                                <li>@Html.ActionLink("Izmena artikla", "IzmeniArtikal", "Artikal")</li>
                                <li>@Html.ActionLink("Brisanje artikla", "BrisanjeArtikla", "Artikal")</li>
                                <li>@Html.ActionLink("Skidanje sa stanja", "SkidanjeSaStanja", "Artikal")</li>
                                <li>@Html.ActionLink("Pretraga artikala", "PretragaArtikala", "Artikal")</li>

                            </ul>

                        </li>
                        @if (User.IsInRole("Menadzer"))
                        {
                            <li class="sideItem" onclick="openSubitem2('subitem2')">
                                Radnici
                            </li>
                            <li>
                                <ul class="nav navbar-nav subitem" id="subitem2" style="display:none; width: 100% !important">
                                    <li>@Html.ActionLink("Lista radnika", "Index", "Radnik")</li>
                                    <li>@Html.ActionLink("Izmena radnika", "IzmenaRadnika", "Radnik")</li>
                                    <li>@Html.ActionLink("brisanje radnika", "BrisanjeRadnika", "Radnik")</li>
                                    <li>@Html.ActionLink("trazi radnika", "TraziRadnika", "Radnik")</li>

                                    <li>@Html.ActionLink("dodavanje radnika", "Register", "Account")</li>
                                </ul>

                            </li>
                            <li class="sideItem" onclick="openSubitem3('subitem3')">
                                Otpremnice
                            </li>
                            <li>
                                <ul class="nav navbar-nav subitem" id="subitem3" style="display:none; width: 100% !important">
                                    <li>@Html.ActionLink("Kreiranje otpremnice", "KreiranjeOtpremnice", "Otpremnica")</li>
                                    <li>@Html.ActionLink("Pretraga kalkulacija", "PretragaKalkulacija", "Otpremnica")</li>
                                    <li>@Html.ActionLink("Lista otpremnica", "TraziKalkulaciju", "Otpremnica")</li>
                                </ul>

                            </li>
                        }
                    </ul>
                
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
       
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - W-Manager</p>
        </footer>
    </div>

    <script>

    function openSidebar() {
        if (document.getElementById('sidebar').style.display == 'none') {
            document.getElementById('sidebar').style.display = 'inline-grid';
        }
        else if (document.getElementById('sidebar').style.display == 'inline-grid') {
            document.getElementById('sidebar').style.display = 'none';
        }
       
    }

    function openSubitem() {
        if (document.getElementById('subitem').style.display == 'none') {
            document.getElementById('subitem').style.display = 'inline-grid';
        }
        else if (document.getElementById('subitem').style.display == 'inline-grid') {
            document.getElementById('subitem').style.display = 'none';
        }
    }
     function openSubitem2() {
         if (document.getElementById('subitem2').style.display == 'none') {
             document.getElementById('subitem2').style.display = 'inline-grid';
         }
         else if (document.getElementById('subitem2').style.display == 'inline-grid') {
             document.getElementById('subitem2').style.display = 'none';
         }
    }
    function openSubitem3() {
        if (document.getElementById('subitem3').style.display == 'none') {
            document.getElementById('subitem3').style.display = 'inline-grid';
        }
        else if (document.getElementById('subitem3').style.display == 'inline-grid') {
            document.getElementById('subitem3').style.display = 'none';
        }
    }


    </script>




    @Scripts.Render("~/Scripts/Layout/toggle.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/myScripts")
    @RenderSection("scripts", required: false)
    @if (TempData["AlertSuccess"] != null)
    {
        <script>
             Lobibox.notify('success', {
             pauseDelayOnHover: true,
             continueDelayOnInactiveTab: false,
             msg: "@TempData["AlertSuccess"]",
             title: 'Uspeh'
             });
        </script>
    }
    @if (TempData["AlertError"] != null)
    {
        <script>
             Lobibox.notify('error', {
             pauseDelayOnHover: true,
             continueDelayOnInactiveTab: false,
             msg: "@TempData["AlertError"]",
             title: 'Greška'
    });
        </script>
    }
</body>
</html>