WManager/Models/DetaljiOtpremniceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WManager.Models
{
    public class DetaljiOtpremniceViewModel
    {
        public DetaljiOtpremniceViewModel()
        {
            Stavke = new List<StavkaOtpremnice>();
        }
        public Otpremnica Otpremnica { get; set; }
        public ApplicationUser Menadzer { get; set; }
        public List<StavkaOtpremnice> Stavke { get; set; }
       
    }
}

WManager/Models/Otpremnica.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WManager.Models
{
    public class Otpremnica
    {
        
        
        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int OtpremnicaId { get; set; }
        [Required]
        [ForeignKey("Menadzer")]
        public string MenadzerId { get; set; }
        
        public ApplicationUser Menadzer { get; set; }
        [Required]
        public string Lokacija { get; set; }
        [Required]
        public DateTime Datum { get; set; }
        public List<StavkaOtpremnice> Stavke { get; set; }
    }
}

WManager/Controllers/OtpremnicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WManager.Models;

namespace WManager.Controllers
{
    [Authorize(Roles = "Menadzer")]
    public class OtpremnicaController : Controller
    {
        ApplicationDbContext context;

        public OtpremnicaController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Otpremnica
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult KreiranjeOtpremnice()
        {
            return View();
        }
        /// <summary>
        /// Kreira novu otpremnicu
        /// </summary>
        /// <param name="id">ID otpremnice</param>
        /// <param name="mesto">Mesto otpremnice</param>
        /// <param name="stavke">Stavke otpremnice</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult KreiranjeOtpremnice(int id, string mesto, List<StavkaOtpremnice> stavke)
        {
            Otpremnica otpremnica = new Otpremnica();
            ApplicationUser menadzer = context.Users.First(x => x.UserName == User.Identity.Name);
            otpremnica.OtpremnicaId = id;
            otpremnica.Menadzer = menadzer;
            otpremnica.Lokacija = mesto;
            otpremnica.Datum = DateTime.Now;
            context.Otpremnice.Add(otpremnica);

            foreach (StavkaOtpremnice s in stavke)
            {
                s.OtpremnicaId = id;

                context.StavkeOtpremnice.Add(s);
                context.Artikli.First(x => x.Barkod == s.Barkod).Kolicina -= s.Kolicina;
            }

            context.SaveChanges();
            return Json("");

        }

        /// <summary>
        /// Vraca stranicu za pretragu kalkulacija
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult PretragaKalkulacija()
        {
            return View();
        }

        [HttpGet]
        public ActionResult TraziKalkulaciju(int OtpremnicaId =0,string Lokacija = "", string Datum = "")
        {
            IQueryable<Otpremnica> kveri = context.Otpremnice;
            if(OtpremnicaId != 0)
            {
                kveri = kveri.Where(x => x.OtpremnicaId == OtpremnicaId);
            }
            if(Lokacija != "")
            {
                kveri = kveri.Where(x => x.Lokacija == Lokacija);
            }
            if(Datum != "")
            {
                DateTime dat = new DateTime();
                try
                {
                    dat = Convert.ToDateTime(Datum);
                }
                catch(Exception ex)
                {
                    TempData["AlertError"] = "Uneti datum je pogresnog formata";
                    return RedirectToAction("PretragaKalkulacija");
                }
                kveri = kveri.Where(x => x.Datum.Year == dat.Year && x.Datum.Month == dat.Month && x.Datum.Day == dat.Day);
            }
            
            List<Otpremnica> otpremnice = kveri.ToList();
           if(otpremnice.Count == 1)
            {
                DetaljiOtpremniceViewModel vm = new DetaljiOtpremniceViewModel();
               
                vm.Otpremnica =otpremnice[0];
                vm.Menadzer = context.Users.FirstOrDefault(x=>x.Id == vm.Otpremnica.MenadzerId);
                List<StavkaOtpremnice> stavke = context.StavkeOtpremnice.Where(x => x.OtpremnicaId == vm.Otpremnica.OtpremnicaId).ToList();
                foreach(StavkaOtpremnice s in stavke)
                {
                    s.Artikal = context.Artikli.FirstOrDefault(x => x.Barkod == s.Barkod);
                }
                vm.Stavke = stavke;
                return View("DetaljiOtpremnice",vm);
            }
            return View(otpremnice);
        }
        /// <summary>
        /// Za ajax, vrsi proveru da li artikal postoji i vraca status kod i artikal
        /// status kodovi: 0-nijeNadjen 1-nadjen 2-Neka druga greska
        /// </summary>
        /// <param name="Barkod">Barkod artikla koji se trazi</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult TraziOtpremnicu(int OtpremnicaId = 0)
        {
            if (OtpremnicaId == 0)
            {
                return Json(new { status = 2 });
            }

            
                Otpremnica o = context.Otpremnice.FirstOrDefault(x => x.OtpremnicaId == OtpremnicaId);
                if (o != null)
                {
                    return Json(new { status = 1, otpremnica = o });
                }
                else
                {
                    return Json(new { status = 0 });
                }
            
           
        }
        [HttpPost]
        public JsonResult VratiSveArtikle(int OtpremnicaId = 0)
        {
            return Json(new { artikli=context.Artikli.Select( x => new { barkod= x.Barkod,naziv = x.Naziv } ).ToList() });

        }
        [HttpPost]
        public JsonResult VratiStanje(string barkod)
        {
            return Json(new { stanje = context.Artikli.Where(x => x.Barkod == barkod).Select(x => x.Kolicina).First() });
        }
    }
}

WManager/Views/Otpremnica/DetaljiOtpremnice.cshtml
@model WManager.Models.DetaljiOtpremniceViewModel
@{
    ViewBag.Title = "DetaljiOtpremnice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <form class="tableForm">
        <h2>DetaljiOtpremnice</h2>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Otpremnica.OtpremnicaId)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Otpremnica.OtpremnicaId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Otpremnica.Lokacija)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Otpremnica.Lokacija)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Otpremnica.Datum)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Otpremnica.Datum)
            </dd>
        </dl>
        <hr />
        <h3>Menadzer</h3>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Menadzer.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Menadzer.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Menadzer.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Menadzer.FirstName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Menadzer.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Menadzer.LastName)
            </dd>
        </dl>
        <hr />
        <h3>Stavke otpremnice</h3>
        <br />
        <table class="table" id="otpremniceTable">
            <thead>
                <tr>
                    <th>
                        Barkod
                    </th>
                    <th>
                        Naziv
                    </th>
                    <th>
                        Kolicina
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Stavke)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Barkod)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Artikal.Naziv)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Kolicina)
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </form>
@section Scripts{

    <script src="~/Scripts/datatables/datatables.min.js"></script>
    <link href="~/Scripts/datatables/datatables.min.css" rel="stylesheet" />
    <script>
        $(document).ready(function () {
            $('#otpremniceTable').DataTable();
        });
    </script>
}

WManager/Views/Otpremnica/KreiranjeOtpremnice.cshtml
@model WManager.Models.Otpremnica

@{
    ViewBag.Title = "KreiranjeOtpremnice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm(new { @class="tableForm"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Otpremnica</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.OtpremnicaId, "Otpremnica Id", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OtpremnicaId, new { htmlAttributes = new { @class = "form-control", @id = "otpremnicaId" } })
            @Html.ValidationMessageFor(model => model.OtpremnicaId, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-2">
            <button id="dugmeTrazi" type="button" class="btnTrazi" onclick="proveriOtpremnicu()">Trazi otpremnicu</button>
        </div>
    </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lokacija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lokacija, new { htmlAttributes = new { @class = "form-control shouldCheckFirst", @id = "Lokacija" } })
                @Html.ValidationMessageFor(model => model.Lokacija, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="stavkeOtpremnice" style="padding-left:30%;">
                <div id="pocetakStavki"></div>
                
            </div>
            <button  onclick="dodajStavku()" class="btnTrazi shouldCheckFirst" type="button"><i class="glyphicon glyphicon-plus"></i> </button>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button onclick="dodajOtpremnicu()" type="button" class="btnTrazi shouldCheckFirst" >Dodaj otpremnicu</button>
                
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
    var brojStavki = 0;
    var stavke = "<option value=\"0\">Odaberite artikal</option>";
    $(window).on("load", function () {
        $.ajax({
                type: "POST",
                url: '@Url.Action("VratiSveArtikle","Otpremnica")',
                data: '{OtpremnicaId: "' + document.getElementById("otpremnicaId").value + '"}',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
            success: function (data) {
                for (i in data.artikli) {
                    stavke += "<option value=\"" + data.artikli[i].barkod + "\">" + data.artikli[i].naziv + " (" + data.artikli[i].barkod + ") " + "</option>";
                }
                }

            });
    });
    function proveriUneto() {
         var idOtpremnice = document.getElementById("otpremnicaId").value;
        var mesto = document.getElementById("Lokacija").value;
        var stavke = document.getElementsByClassName("stavka");

        if (idOtpremnice == "" || mesto == "") {
            porukaNeuspeh("Polja Id otpremnice i mesto moraju biti popunjena!");
            return false;
        }
        var barcodes = Array();
        for (var i = 0; i < stavke.length; i++) {
            
            if (stavke[i].getElementsByClassName("stavkaBarkod")[0].value == 0) {
                 porukaNeuspeh("Morate popuniti sve stavke otpremnice!");
                return false;
            }
            if (stavke[i].getElementsByClassName("stavkaKolicina")[0].value <= 0 || (parseInt(stavke[i].getElementsByClassName("stavkaKolicina")[0].getAttribute("max")) < parseInt(stavke[i].getElementsByClassName("stavkaKolicina")[0].value))) {
               
                porukaNeuspeh("Kolicina na otpremnici mora biti izmedju 0 i kolicine artikala na stanju!");
                return false;
            }

            barcodes.push(stavke[i].getElementsByClassName("stavkaBarkod")[0].value);
        }
        var alreadySeen = [];
        var imaDuplikata = false;
       barcodes.forEach(function (str) {
           if (alreadySeen[str]) {
               porukaNeuspeh("Isti artikal unet vise puta! Barkod artikla:" + str);
                imaDuplikata = true;
            }
            else
                alreadySeen[str] = true;
            });
        if (imaDuplikata) {
            return false;
        }
        return true
        
    }
    function dodajOtpremnicu() {
        if (proveriUneto()) {
            var idOtpremnice = document.getElementById("otpremnicaId").value;
            var mesto = document.getElementById("Lokacija").value;
            var stavke = document.getElementsByClassName("stavka");
            var stavkeJSON = "[";

            for (var i = 0; i < stavke.length; i++) {
                if (i != 0) {
                    stavkeJSON += ","
                }
                console.log(stavke[i].getElementsByClassName("stavkaBarkod")[0].value);
                stavkeJSON += "{'Barkod':'" + stavke[i].getElementsByClassName("stavkaBarkod")[0].value + "','Kolicina':'" + stavke[i].getElementsByClassName("stavkaKolicina")[0].value + "'}";
            }
            stavkeJSON += "]";
            var otpremnica = "{ 'id':" + idOtpremnice + "," +
                "'mesto':'" + mesto + "'," +
                "'stavke':" + stavkeJSON +
                "}";
            $.ajax({
                type: "POST",
                url: '@Url.Action("KreiranjeOtpremnice","Otpremnica")',
                data: otpremnica,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    window.location.href = "/";

                }

            });
        }
    }

    function selektovanArtikal(select) {
         $.ajax({
                type: "POST",
                url: '@Url.Action("VratiStanje","Otpremnica")',
                data: '{barkod: "' + select.value + '"}',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
             success: function (data) {
                 console.log(data);
                 select.parentElement.getElementsByTagName("input")[0].value = 1;
                 select.parentElement.getElementsByTagName("input")[0].setAttribute("max", data.stanje); 
                 select.parentElement.getElementsByClassName("maxNaStanju")[0].innerHTML = "broj artikala na stanju: " + data.stanje;

                }

            });
        
    }

    function proveriOtpremnicu() {

        var otpremnicaId = document.getElementById("otpremnicaId").value
        
        if (otpremnicaId !== "") {
            $.ajax({
                type: "POST",
                url: '@Url.Action("TraziOtpremnicu","Otpremnica")',
                data: '{OtpremnicaId: "' + document.getElementById("otpremnicaId").value + '"}',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    if (data.status == 1) {
                        porukaNeuspeh("Otpremnica sa unetim Id vec postoji!");
                        onemoguciPolja();
                    }
                    if (data.status == 0) {
                        porukaUspeh("Ne postoji, nastavi unos");
                        beLazy();
                        dodajStavku();
                        omoguciPolja();
                    }
                    if (data.status == 2) {
                        porukaNeuspeh("Dogodila se greska pri proveri otpremnice!");
                        onemoguciPolja();
                    }
                }

            });
        }
        else {
             porukaNeuspeh("Morate uneti Id otpremnice!");
        }
    }

    function beLazy() {
        document.getElementById("otpremnicaId").setAttribute("readonly", true);
        document.getElementById("dugmeTrazi").setAttribute("disabled", true);
    }

    function dodajStavku() {
        var pocetak = document.getElementById("pocetakStavki");
        pocetak.insertAdjacentHTML("beforebegin",
            "<div class=\"stavka\">" +
            "<h4>Stavka " + (brojStavki + 1) + " :</h4>" +"<hr>"+
            "<b>Odaberite artikal</b>"+
            "<select required=\"\"  onchange=\"selektovanArtikal(this)\" class=\"form-control stavkaBarkod\">" +
            stavke + 
            "</select><br/>" +
            "<i class=\"maxNaStanju\">Broj artikala na stanju: </i><br><br>" +
            "<b>Odaberite broj artikala za dodavanje na otpremnicu</b><br>"+
            "<input required=\"\"  min=\"0\" value=\"1\" type=\"number\" class=\"form-control stavkaKolicina\"/>" +
           
            "</div><br>"
            
        )
        brojStavki += 1;

    }
    </script>
}

WManager/Views/Otpremnica/PretragaKalkulacija.cshtml
@model WManager.Models.Otpremnica

@{
    ViewBag.Title = "TraziKalkulaciju";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@using (Html.BeginForm("TraziKalkulaciju", "Otpremnica", FormMethod.Get, new { @class="tableForm"})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Otpremnica</h4>
        <hr />
        
        <div class="form-group">
            @Html.LabelFor(model => model.OtpremnicaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtpremnicaId, new { htmlAttributes = new { @class = "form-control" } })
               
            </div>
        </div>

       <div class="form-group">
            @Html.LabelFor(model => model.Lokacija, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lokacija, new { htmlAttributes = new { @class = "form-control" } })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Datum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Datum, new { htmlAttributes = new { @class = "form-control" } })
              <p style="color:#ff9955">Uneti datum mora biti formata: mesec/dan/godina </p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Trazi otpremnicu" class="btnTrazi" style="margin-left:70px;" />
            </div>
        </div>
    </div>
}

WManager/Views/Otpremnica/TraziKalkulaciju.cshtml
@model IEnumerable<WManager.Models.Otpremnica>

@{
    ViewBag.Title = "TraziKalkulaciju";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <form class="tableForm">
        <h4>Lista otpremnica</h4>
        <hr />
        <table class="table" id="otpremniceTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.OtpremnicaId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Lokacija)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Datum)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.OtpremnicaId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lokacija)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Datum)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.OtpremnicaId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.OtpremnicaId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.OtpremnicaId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
@section Scripts{

    <script src="~/Scripts/datatables/datatables.min.js"></script>
    <link href="~/Scripts/datatables/datatables.min.css" rel="stylesheet" />
    <script>
        $(document).ready(function () {
            $('#otpremniceTable').DataTable();
        });
    </script>
}